# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Dr. Paula Musuva
email: pmusuva@usiu.ac.ke
description: >- # this means to ignore newlines until "baseurl:"
  Assistant Professor of Information Systems | Researcher | Consultant
twitter_username: pmusuva
github_username: pmmusuva
minimal_mistakes_skin: neon # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 3 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Dr. Paula Musuva"
  avatar : "/assets/images/photo.jpg"
  bio    : "I teach, research, and consult."
  links:
    - label: "Google Scholar"
      icon: "fas fa-fw fa-link"
      url: "https://scholar.google.com/citations?user=CLzA3BQAAAAJ&hl=en"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/pmusuva/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/pmmusuva/"
    - label: "Cyber Shujaa"
      icon: "fas fa-shield-alt"
      url: "https://cybershujaa.co.ke/"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/pmusuva/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/pmmusuva/"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-link"
      url: "https://scholar.google.com/citations?user=CLzA3BQAAAAJ&hl=en"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
